[package]
name = "gringo-language-server"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cc="*"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
tower-lsp = "0.20.0"
tree-sitter = "~0.22.5"
tree-sitter-gringo = { git = "https://github.com/lcian/tree-sitter-gringo" }
